<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Derives the Lexicom.Configuration.AzureKeyVault package to provide an implementation specific for an AspNetCore controller application project.</Description>
    <PackageTags>aspnetcore;azure;dependencyinjection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Configuration.AzureKeyVault\Lexicom.Configuration.AzureKeyVault.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.AspNetCore.Controllers\Lexicom.Supports.AspNetCore.Controllers.csproj" />
  </ItemGroup>

</Project>
