<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Derives the Lexicom.Cryptography package to provide an implementation specific for a testing application project.</Description>
    <PackageTags>dependencyinjection;cryptography</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Cryptography\Lexicom.Cryptography.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.Testing\Lexicom.Supports.Testing.csproj" />
  </ItemGroup>

</Project>
