<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Supplies simple cryptography encryption and decryption systems for use in applications needing minimal security where such a simple implementation is valid. </Description>
    <PackageTags>dependencyinjection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.DependencyInjection.Amenities\Lexicom.DependencyInjection.Amenities.csproj" />
    <ProjectReference Include="..\Lexicom.Validation.Amenities\Lexicom.Validation.Amenities.csproj" />
    <ProjectReference Include="..\Lexicom.Validation.Options\Lexicom.Validation.Options.csproj" />
  </ItemGroup>

</Project>
