<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <Description>Provides useful value converters for WPF application projects.</Description>
    <PackageTags>valueconverters;wpf</PackageTags>
  </PropertyGroup>

</Project>
