<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Derives the Lexicom.Cryptography package to provide an implementation specific for a Blazor web assembly application project.</Description>
    <PackageTags>blazor;dependencyinjection;webassembly</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Cryptography\Lexicom.Cryptography.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.Blazor.WebAssembly\Lexicom.Supports.Blazor.WebAssembly.csproj" />
  </ItemGroup>

</Project>
