<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <Description>Adds functionality for interacting with Wpf application xaml markup programmatically.</Description>
    <PackageTags>wpf</PackageTags>
  </PropertyGroup>

</Project>
