<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds console support to the Lexicom.Configuration.AzureKeyVault package.</Description>
    <PackageTags>configuration;azure;console</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Configuration.AzureKeyVault\Lexicom.Configuration.AzureKeyVault.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.ConsoleApp\Lexicom.Supports.ConsoleApp.csproj" />
  </ItemGroup>

</Project>
