<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds console support to the Lexicom.DependencyInjection.Primitives package.</Description>
    <PackageTags>primitives;dependencyinjection;console</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.DependencyInjection.Primitives\Lexicom.DependencyInjection.Primitives.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.ConsoleApp\Lexicom.Supports.ConsoleApp.csproj" />
  </ItemGroup>

</Project>
