<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>The base package for all Lexicom console packages.</Description>
    <PackageTags>dependencyinjection;console</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.ConsoleApp.DependencyInjection\Lexicom.ConsoleApp.DependencyInjection.csproj" />
    <ProjectReference Include="..\Lexicom.DependencyInjection.Hosting\Lexicom.DependencyInjection.Hosting.csproj" />
  </ItemGroup>

</Project>
