<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Wraps the System.Net.Mail reference standardizing its use and implementation with other Lexicom packages. This primarily consists of enforcing consistent styles and patterns while also generally reducing the required configuration.</Description>
    <PackageTags>dependencyinjection;smtp</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.DependencyInjection.Amenities\Lexicom.DependencyInjection.Amenities.csproj" />
    <ProjectReference Include="..\Lexicom.Extensions.IO\Lexicom.Extensions.IO.csproj" />
    <ProjectReference Include="..\Lexicom.Validation.Amenities\Lexicom.Validation.Amenities.csproj" />
    <ProjectReference Include="..\Lexicom.Validation.Options\Lexicom.Validation.Options.csproj" />
  </ItemGroup>

</Project>
