<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Wraps Microsoft.AspNetCore.Identity to standardize its use and integration with other Lexicom packages.</Description>
    <PackageTags>identity;entityframework;dependencyinjection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <!--Because the 'Microsoft.AspNetCore.Identity' package is deprecated I have to include this framework reference instead.-->
    <!--This is not currently ideal since this package now has this hard dependency but to move it to only the 'Lexicom.EntityFramework.Identity.For.AspNetCore.Controllers' package would cause additional problems.-->
    <!--Todo: move this framework reference to the 'Lexicom.EntityFramework.Identity.For.AspNetCore.Controllers' package.-->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.DependencyInjection.Amenities\Lexicom.DependencyInjection.Amenities.csproj" />
    <ProjectReference Include="..\Lexicom.Validation.Amenities\Lexicom.Validation.Amenities.csproj" />
    <ProjectReference Include="..\Lexicom.Validation.Options\Lexicom.Validation.Options.csproj" />
  </ItemGroup>

</Project>
