<Project>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject Condition="$(MSBuildProjectName.StartsWith('UnitTests.')) or $(MSBuildProjectName.StartsWith('IntegrationTests.'))">true</IsTestProject>
  </PropertyGroup>

  <!--shared nuget package metadata for every publishable library project-->
  <PropertyGroup Condition="'$(IsTestProject)' != 'true'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>lexicom.nuget.icon.png</PackageIcon>
    <Authors>Alex Stroot</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>2026</Copyright>
    <PackageProjectUrl>https://github.com/AlexLexicon/Lexicom/tree/master/$(MSBuildProjectName)</PackageProjectUrl>
    <RepositoryUrl>https://github.com/AlexLexicon/Lexicom</RepositoryUrl>
    <RepositoryType>github</RepositoryType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestProject)' != 'true'">
    <None Include="$(MSBuildThisFileDirectory)lexicom.nuget.icon.png" Pack="true" PackagePath="\" Visible="false" />
    <None Include="$(MSBuildProjectDirectory)\README.md" Pack="true" PackagePath="\" Condition="Exists('$(MSBuildProjectDirectory)\README.md')" />
  </ItemGroup>

</Project>
