<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds console support to the Lexicom.Validation package.</Description>
    <PackageTags>validation;fluentvalidation;dependencyinjection;console</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Supports.ConsoleApp\Lexicom.Supports.ConsoleApp.csproj" />
    <ProjectReference Include="..\Lexicom.Validation\Lexicom.Validation.csproj" />
  </ItemGroup>

</Project>
