<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds console support to the Lexicom.EntityFramework.Identity package.</Description>
    <PackageTags>identity;entityframework;dependencyinjection;console</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.EntityFramework.Identity\Lexicom.EntityFramework.Identity.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.ConsoleApp\Lexicom.Supports.ConsoleApp.csproj" />
  </ItemGroup>

</Project>
