<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <Description>The base package for all Lexicom WPF packages.</Description>
    <PackageTags>dependencyinjection;wpf</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.DependencyInjection.Hosting\Lexicom.DependencyInjection.Hosting.csproj" />
    <ProjectReference Include="..\Lexicom.Wpf.DependencyInjection\Lexicom.Wpf.DependencyInjection.csproj" />
  </ItemGroup>

</Project>
