<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds Blazor WebAssembly support to the Lexicom.DependencyInjection.Primitives package.</Description>
    <PackageTags>primitives;dependencyinjection;blazor;webassembly</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.DependencyInjection.Primitives\Lexicom.DependencyInjection.Primitives.csproj" />
    <ProjectReference Include="..\Lexicom.Validation.For.Blazor.WebAssembly\Lexicom.Validation.For.Blazor.WebAssembly.csproj" />
  </ItemGroup>

</Project>
