<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>The base package for all Lexicom...For.Blazor.WebAssembly packages. Relies on and enforces the inclusion of the Microsoft.AspNetCore.Components.WebAssembly package reference.</Description>
    <PackageTags>blazor;webassembly;dependencyinjection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.DependencyInjection.Hosting\Lexicom.DependencyInjection.Hosting.csproj" />
  </ItemGroup>

</Project>
