<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Abstractions for the Lexicom.Wpf.DependencyInjection. Allowing this package to not enforce a target framework including windows.</Description>
    <PackageTags>dependencyinjection;wpf</PackageTags>
  </PropertyGroup>

</Project>
