<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds convenient but optional features for any Console application project. Although not necessary these features are specifically designed to integrate with other Lexicom Console application packages.</Description>
    <PackageTags>console;dependencyinjection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
