<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds ASP.NET Core controller support to the Lexicom.Logging package.</Description>
    <PackageTags>logging;serilog;dependencyinjection;aspnetcore</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Logging\Lexicom.Logging.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.AspNetCore.Controllers\Lexicom.Supports.AspNetCore.Controllers.csproj" />
  </ItemGroup>

</Project>
