<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds ASP.NET Core controller support to the Lexicom.Authority package.</Description>
    <PackageTags>authority;jwt;dependencyinjection;aspnetcore</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Authority\Lexicom.Authority.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.AspNetCore.Controllers\Lexicom.Supports.AspNetCore.Controllers.csproj" />
  </ItemGroup>

</Project>
