<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <Description>Adds WPF support to the Lexicom.Cryptography package.</Description>
    <PackageTags>cryptography;dependencyinjection;wpf</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Cryptography\Lexicom.Cryptography.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.Wpf\Lexicom.Supports.Wpf.csproj" />
  </ItemGroup>

</Project>
