<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds ASP.NET Core controller support to the Lexicom.Authorization package.</Description>
    <PackageTags>authorization;jwt;dependencyinjection;aspnetcore</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Authorization\Lexicom.Authorization.csproj" />
    <ProjectReference Include="..\Lexicom.Jwt\Lexicom.Jwt.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.AspNetCore.Controllers\Lexicom.Supports.AspNetCore.Controllers.csproj" />
  </ItemGroup>

</Project>
