<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>A rigid text user interface for a Console application specifically designed to execute different operations from the command line. Specifically implemented to be fast and easy to setup. Ideal for utility style tools.</Description>
    <PackageTags>console;dependencyinjection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.ConsoleApp.DependencyInjection\Lexicom.ConsoleApp.DependencyInjection.csproj" />
    <ProjectReference Include="..\Lexicom.DependencyInjection.Amenities\Lexicom.DependencyInjection.Amenities.csproj" />
    <ProjectReference Include="..\Lexicom.Extensions.Reflection\Lexicom.Extensions.Reflection.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.ConsoleApp\Lexicom.Supports.ConsoleApp.csproj" />
  </ItemGroup>

</Project>
