<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds ASP.NET Core controller support to the Lexicom.Authentication package.</Description>
    <PackageTags>authentication;jwt;dependencyinjection;aspnetcore</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.AspNetCore.Controllers.Amenities\Lexicom.AspNetCore.Controllers.Amenities.csproj" />
    <ProjectReference Include="..\Lexicom.Authentication\Lexicom.Authentication.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.AspNetCore.Controllers\Lexicom.Supports.AspNetCore.Controllers.csproj" />
  </ItemGroup>

</Project>
