<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <Description>Adds WPF support to the Lexicom.Configuration.AzureKeyVault package.</Description>
    <PackageTags>configuration;azure;wpf</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Configuration.AzureKeyVault\Lexicom.Configuration.AzureKeyVault.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.Wpf\Lexicom.Supports.Wpf.csproj" />
  </ItemGroup>

</Project>
