<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <Description>Derives the Lexicom.Configuration.AzureKeyVault package to provide an implementation specific for a Wpf application project.</Description>
    <PackageTags>azure;dependencyinjection;wpf</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Configuration.AzureKeyVault\Lexicom.Configuration.AzureKeyVault.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.Wpf\Lexicom.Supports.Wpf.csproj" />
  </ItemGroup>

</Project>
