<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <Description>Supplies useful attached properties for any Wpf application project.</Description>
    <PackageTags>wpf</PackageTags>
  </PropertyGroup>

</Project>
