<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds convenient but optional features for any project utilizing entity framework.</Description>
    <PackageTags>dependencyinjection;entityframework</PackageTags>
  </PropertyGroup>

</Project> 
