<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <Description>Adds WPF support to the Lexicom.Validation package.</Description>
    <PackageTags>validation;fluentvalidation;dependencyinjection;wpf</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Supports.Wpf\Lexicom.Supports.Wpf.csproj" />
    <ProjectReference Include="..\Lexicom.Validation\Lexicom.Validation.csproj" />
  </ItemGroup>

</Project>
