<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Derives the Lexicom.Scalar package to provide an implementation specific for an AspNetCore controller application project.</Description>
    <PackageTags>aspnetcore;dependencyinjection;scalar</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Scalar\Lexicom.Scalar.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.AspNetCore.Controllers\Lexicom.Supports.AspNetCore.Controllers.csproj" />
  </ItemGroup>

</Project>
