<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>A basis for any authentication features and or functionality to be further implemented manually or by a derivative package.</Description>
    <PackageTags>authentication;dependencyinjection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <!--We need to be able to call AddAuthentication which is only possible by using this framework reference.-->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Jwt\Lexicom.Jwt.csproj" />
  </ItemGroup>

</Project>
