<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Provides interfaces for basic types that are otherwise not commonly used in conjunction with dependency injection but technically act as IO operations and as such should be classified as a separate dependency.</Description>
    <PackageTags>dependencyinjection</PackageTags>
  </PropertyGroup>

</Project>
