<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Adds console support to the Lexicom.Smtp package.</Description>
    <PackageTags>smtp;dependencyinjection;console</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Smtp\Lexicom.Smtp.csproj" />
    <ProjectReference Include="..\Lexicom.Validation.For.ConsoleApp\Lexicom.Validation.For.ConsoleApp.csproj" />
  </ItemGroup>

</Project>
