<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Derives the Lexicom.Smtp package to provide an implementation specific for a Console application project.</Description>
    <PackageTags>console;dependencyinjection;smtp</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Smtp\Lexicom.Smtp.csproj" />
    <ProjectReference Include="..\Lexicom.Validation.For.ConsoleApp\Lexicom.Validation.For.ConsoleApp.csproj" />
  </ItemGroup>

</Project>
