<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Derives the Lexicom.Mvvm package to provide an implementation specific for a testing application project.</Description>
    <PackageTags>dependencyinjection;mvvm</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Mvvm\Lexicom.Mvvm.csproj" />
    <ProjectReference Include="..\Lexicom.Supports.Testing\Lexicom.Supports.Testing.csproj" />
  </ItemGroup>

</Project>
