<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Description>Provides FluentValidation support for Microsoft.Extensions.Options.</Description>
    <PackageTags>validation;options;fluentvalidation;dependencyinjection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <!--the OptionsBuilder.ValidateOnStart() method is only in this package. For some reason the Abstractions package does not include this which is lame.-->
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Extensions.CompilerServices\Lexicom.Extensions.CompilerServices.csproj" />
    <ProjectReference Include="..\Lexicom.Extensions.Exceptions\Lexicom.Extensions.Exceptions.csproj" />
    <ProjectReference Include="..\Lexicom.Validation\Lexicom.Validation.csproj" />
  </ItemGroup>

</Project>
